server:
  port: 9292

spring:
  application:
    name: idam-health-check

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /admin
      path-mapping:
        health: health
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true
  health:
    defaults:
      enabled: false

azure:
  application-insights:
    instrumentation-key:
#  keyvault:
#    uri:
#    client-id:
#    client-key:
#    msi:
#      url: http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fvault.azure.net
#      error:
#        retry:
#          max-number: 3
#          interval-millis: 0

feign:
  okhttp:
    enabled: false
  httpclient:
    enabled: true

ldap:
  root: ldaps://dummy:1639
  principal: CN=Directory Manager
  replication:
    missing-updates-threshold: 999
    approximate-delay-threshold: 120000

userstore:
  healthprobe:
    authentication:
      freshness-interval: 6000
      check-interval: 1000
    replication:
      freshness-interval: 6000
      check-interval: 1000

tokenstore:
  healthprobe:
    search:
      freshness-interval: 6000
      check-interval: 1000
    replication:
      freshness-interval: 6000
      check-interval: 1000

idm:
  root: https://dummy
  healthprobe:
    ping:
      freshness-interval: 6000
      check-interval: 1000

am:
  root: https://dummy
  healthprobe:
    isAlive:
      freshness-interval: 6000
      check-interval: 1000
    passwordGrant:
      freshness-interval: 86400000
      check-interval: 7200000
    identity:
      scope: openid profile authorities acr roles
      host: dummy

backup:
  healthprobe:
    full:
      name: FullBackup
      freshness-interval: 93600000
      check-interval: 300000
      path: /opt/opendj/bak/full/userRoot/backup.info
      expiry-interval: 93600000
    incremental:
      name: IncrementalBackup
      freshness-interval: 360000
      check-interval: 120000
      path: /opt/opendj/bak/incremental/userRoot/backup.info
      expiry-interval: 420000

replication:
  healthprobe:
    command:
      name: ReplicationCommand
      freshness-interval: 180000
      check-interval: 60000
      template: /opt/opendj/bin/dsreplication status -X --adminUID amadmin --adminPassword %s --port 4444 -s -n
      host-identity: forgerock-ds-userstore-1
      missing-updates-threshold: 999
      command-timeout: 20000