spring:
  application:
    name: idam-health-check

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true
  health:
    defaults:
      enabled: false

azure:
  application-insights:
    instrumentation-key: 3981751e-f34d-42e8-a4e4-062cc01d5bc0

ldap:
  root: ldaps://dummy:1639
  principal: CN=Directory Manager

userstore:
  healthprobe:
    authentication:
      freshness-interval: 30000
      check-interval: 10000

tokenstore:
  healthprobe:
    search:
      freshness-interval: 30000
      check-interval: 10000

idm:
  healthprobe:
    ping:
      freshness-interval: 30000
      check-interval: 10000