server:
  port: 9292

spring:
  application:
    name: idam-health-check

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /admin
      path-mapping:
        health: health
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true
  health:
    defaults:
      enabled: false

azure:
  application-insights:
    instrumentation-key:
#  keyvault:
#    uri:
#    client-id:
#    client-key:

ldap:
  root: ldaps://dummy:1639
  principal: CN=Directory Manager
  replication:
    missing-changes-threshold: 0
    pending-updates-threshold: 0

userstore:
  healthprobe:
    authentication:
      freshness-interval: 5000
      check-interval: 5000
    replication:
      freshness-interval: 5000
      check-interval: 5000

tokenstore:
  healthprobe:
    search:
      freshness-interval: 5000
      check-interval: 5000
    replication:
      freshness-interval: 5000
      check-interval: 5000

idm:
  root: https://dummy
  healthprobe:
    ping:
      freshness-interval: 5000
      check-interval: 5000

am:
  root: https://dummy
  healthprobe:
    isAlive:
      freshness-interval: 5000
      check-interval: 5000
    passwordGrant:
      freshness-interval: 70000
      check-interval: 60000
    identity:
      scope: openid profile authorities acr roles
      host: dummy