spring:
  application:
    name: idam-health-check

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true
  health:
    defaults:
      enabled: false

azure:
  application-insights:
    instrumentation-key: dummy
  keyvault:
    uri: https://dummy.vault.azure.net/
    client-id: dummy
    client-key: dummy

ldap:
  root: ldaps://dummy:1639
  principal: CN=Directory Manager

userstore:
  healthprobe:
    authentication:
      freshness-interval: 30000
      check-interval: 10000

tokenstore:
  healthprobe:
    search:
      freshness-interval: 30000
      check-interval: 10000

idm:
  root: https://dummy
  healthprobe:
    ping:
      freshness-interval: 30000
      check-interval: 10000

am:
  healthprobe:
    isAlive:
      freshness-interval: 30000
      check-interval: 10000
    passwordGrant:
      freshness-interval: 60000
      check-interval: 45000
    identity:
      scope: openid profile authorities acr roles