server:
  port: 9292

spring:
  application:
    name: idam-health-check

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /admin
      path-mapping:
        health: health
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true
  health:
    defaults:
      enabled: false

azure:
  application-insights:
    instrumentation-key:
#  keyvault:
#    uri:
#    client-id:
#    client-key:
#    msi:
#      url: http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fvault.azure.net
#      error:
#        retry:
#          max-number: 3
#          interval-millis: 0

feign:
  okhttp:
    enabled: false
  httpclient:
    enabled: true

ldap:
  root: ldaps://dummy:1639
  principal: CN=Directory Manager
  replication:
    missing-changes-threshold: 10
    pending-updates-threshold: 10

userstore:
  healthprobe:
    authentication:
      freshness-interval: 6000
      check-interval: 1000
    replication:
      freshness-interval: 6000
      check-interval: 1000

tokenstore:
  healthprobe:
    search:
      freshness-interval: 6000
      check-interval: 1000
    replication:
      freshness-interval: 6000
      check-interval: 1000

idm:
  root: https://dummy
  healthprobe:
    ping:
      freshness-interval: 6000
      check-interval: 1000

am:
  root: https://dummy
  healthprobe:
    isAlive:
      freshness-interval: 6000
      check-interval: 1000
    passwordGrant:
      freshness-interval: 86400000
      check-interval: 7200000
    identity:
      scope: openid profile authorities acr roles
      host: dummy