ldap:
  root: ldaps://forgerock-ds-tokenstore:1636
  principal: CN=dummy
  password: dummy
  partitionSuffix:

tokenstore:
  healthprobe:
    search:
      freshness:
        interval: 30000
      check:
        interval: 10000